package anthropic

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

const (
	apiURL      = "https://api.anthropic.com/v1/messages"
	apiVersion  = "2023-06-01"
	toolName    = "create_trello_card"

	// DefaultModel and DefaultMaxTokens are used when the plugin settings leave these fields blank.
	DefaultModel     = "claude-sonnet-4-6"
	DefaultMaxTokens = 1024

	// coreSystemPrompt describes the assistant's role.  The output structure is enforced by the
	// tool schema below rather than by prose instructions, so admins cannot accidentally break
	// card parsing regardless of what they put in the additional-context fields.
	coreSystemPrompt = `You are a project management assistant that creates structured Trello cards from Mattermost thread messages.`
)

// cardInputSchema is the JSON Schema used for the forced-tool-use call.
// Using tool_choice forces Claude to always return valid JSON matching this schema.
var cardInputSchema = json.RawMessage(`{
	"type": "object",
	"properties": {
		"title": {
			"type": "string",
			"description": "A concise card title, maximum 60 characters."
		},
		"description": {
			"type": "string",
			"description": "A clear description of the issue or task. Always include the Mattermost thread link provided by the user."
		},
		"checklist": {
			"type":  "array",
			"items": {"type": "string"},
			"description": "3 to 7 short, actionable checklist items."
		}
	},
	"required": ["title", "description", "checklist"]
}`)

// Client is a minimal Anthropic messages API client.
type Client struct {
	APIKey string
}

// CardContent is the structured output generated by Claude for a Trello card.
type CardContent struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Checklist   []string `json:"checklist"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicTool struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	InputSchema json.RawMessage `json:"input_schema"`
}

type anthropicToolChoice struct {
	Type string `json:"type"`
	Name string `json:"name"`
}

type anthropicRequest struct {
	Model      string              `json:"model"`
	MaxTokens  int                 `json:"max_tokens"`
	System     string              `json:"system"`
	Tools      []anthropicTool     `json:"tools"`
	ToolChoice anthropicToolChoice `json:"tool_choice"`
	Messages   []anthropicMessage  `json:"messages"`
}

type anthropicContent struct {
	Type  string          `json:"type"`
	Input json.RawMessage `json:"input,omitempty"` // populated for tool_use blocks
}

type anthropicResponse struct {
	Content []anthropicContent `json:"content"`
	Error   *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// GenerateCardContent calls the Anthropic API using forced tool use and returns structured
// Trello card content derived from the user's message.
//
// Forced tool use (tool_choice: {type: "tool"}) guarantees that the response is always valid
// JSON matching the card schema — no markdown fences, no prose, no parsing heuristics needed.
//
// model and maxTokens fall back to DefaultModel / DefaultMaxTokens when zero-valued.
// additionalContext, if non-empty, is appended to the core system prompt so that
// admin-supplied company/bot context reaches Claude without affecting output structure.
func (c *Client) GenerateCardContent(userMessage, threadLink, model string, maxTokens int, additionalContext string) (*CardContent, error) {
	if model == "" {
		model = DefaultModel
	}
	if maxTokens <= 0 {
		maxTokens = DefaultMaxTokens
	}

	systemPmt := coreSystemPrompt
	if additionalContext != "" {
		systemPmt += "\n\n" + additionalContext
	}

	userPrompt := fmt.Sprintf(
		"Create a Trello card for the following issue. The Mattermost thread link is: %s\n\nIssue description: %s",
		threadLink, userMessage,
	)

	reqBody := anthropicRequest{
		Model:     model,
		MaxTokens: maxTokens,
		System:    systemPmt,
		Tools: []anthropicTool{
			{
				Name:        toolName,
				Description: "Create a structured Trello card from the user's Mattermost message.",
				InputSchema: cardInputSchema,
			},
		},
		ToolChoice: anthropicToolChoice{Type: "tool", Name: toolName},
		Messages: []anthropicMessage{
			{Role: "user", Content: userPrompt},
		},
	}

	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("anthropic: failed to marshal request: %w", err)
	}

	req, err := http.NewRequest(http.MethodPost, apiURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("anthropic: failed to create request: %w", err)
	}
	req.Header.Set("x-api-key", c.APIKey)
	req.Header.Set("anthropic-version", apiVersion)
	req.Header.Set("content-type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("anthropic: request failed: %w", err)
	}
	defer resp.Body.Close()

	respBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("anthropic: failed to read response: %w", err)
	}

	var apiResp anthropicResponse
	if err = json.Unmarshal(respBytes, &apiResp); err != nil {
		return nil, fmt.Errorf("anthropic: failed to parse response: %w", err)
	}

	if apiResp.Error != nil {
		return nil, fmt.Errorf("anthropic: API error: %s", apiResp.Error.Message)
	}

	// Find the tool_use block; with forced tool_choice this will always be present.
	for _, block := range apiResp.Content {
		if block.Type == "tool_use" {
			var card CardContent
			if err = json.Unmarshal(block.Input, &card); err != nil {
				return nil, fmt.Errorf("anthropic: failed to parse card from tool input: %w", err)
			}
			return &card, nil
		}
	}

	return nil, fmt.Errorf("anthropic: no tool_use block in response")
}
