package anthropic

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

const (
	apiURL      = "https://api.anthropic.com/v1/messages"
	apiVersion  = "2023-06-01"

	// DefaultModel and DefaultMaxTokens are used when the plugin settings leave these fields blank.
	DefaultModel     = "claude-sonnet-4-6"
	DefaultMaxTokens = 1024

	// coreSystemPrompt contains the immutable JSON-output instructions that admins cannot override,
	// ensuring the response format is always valid for Trello card creation.
	// Any admin-supplied additional context is appended after this block at call time.
	coreSystemPrompt = `You are a project management assistant that creates structured Trello cards from user messages.
You must respond with ONLY a valid JSON object and nothing else — no prose, no markdown fences.
The JSON object must have exactly these fields:
  "title"       – A concise card title, maximum 60 characters.
  "description" – A clear description of the issue or task. Always include the Mattermost thread link provided by the user.
  "checklist"   – An array of strings, each being a short, actionable checklist item (3–7 items).`
)

// Client is a minimal Anthropic messages API client.
type Client struct {
	APIKey string
}

// CardContent is the structured output generated by Claude for a Trello card.
type CardContent struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Checklist   []string `json:"checklist"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicRequest struct {
	Model     string             `json:"model"`
	MaxTokens int                `json:"max_tokens"`
	System    string             `json:"system"`
	Messages  []anthropicMessage `json:"messages"`
}

type anthropicContent struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

type anthropicResponse struct {
	Content []anthropicContent `json:"content"`
	Error   *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// GenerateCardContent calls the Anthropic API and returns structured Trello card content
// derived from the user's message.
//
// model and maxTokens fall back to DefaultModel / DefaultMaxTokens when zero-valued.
// additionalContext, if non-empty, is appended to the core system prompt so that
// admin-supplied company/bot context reaches Claude without touching the JSON-output
// instructions that must remain intact.
func (c *Client) GenerateCardContent(userMessage, threadLink, model string, maxTokens int, additionalContext string) (*CardContent, error) {
	if model == "" {
		model = DefaultModel
	}
	if maxTokens <= 0 {
		maxTokens = DefaultMaxTokens
	}

	systemPmt := coreSystemPrompt
	if additionalContext != "" {
		systemPmt += "\n\n" + additionalContext
	}

	userPrompt := fmt.Sprintf(
		"Create a Trello card for the following issue. The Mattermost thread link is: %s\n\nIssue description: %s",
		threadLink, userMessage,
	)

	reqBody := anthropicRequest{
		Model:     model,
		MaxTokens: maxTokens,
		System:    systemPmt,
		Messages: []anthropicMessage{
			{Role: "user", Content: userPrompt},
		},
	}

	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("anthropic: failed to marshal request: %w", err)
	}

	req, err := http.NewRequest(http.MethodPost, apiURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("anthropic: failed to create request: %w", err)
	}
	req.Header.Set("x-api-key", c.APIKey)
	req.Header.Set("anthropic-version", apiVersion)
	req.Header.Set("content-type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("anthropic: request failed: %w", err)
	}
	defer resp.Body.Close()

	respBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("anthropic: failed to read response: %w", err)
	}

	var apiResp anthropicResponse
	if err = json.Unmarshal(respBytes, &apiResp); err != nil {
		return nil, fmt.Errorf("anthropic: failed to parse response: %w", err)
	}

	if apiResp.Error != nil {
		return nil, fmt.Errorf("anthropic: API error: %s", apiResp.Error.Message)
	}

	if len(apiResp.Content) == 0 {
		return nil, fmt.Errorf("anthropic: empty response content")
	}

	var card CardContent
	if err = json.Unmarshal([]byte(apiResp.Content[0].Text), &card); err != nil {
		return nil, fmt.Errorf("anthropic: failed to parse card JSON from response: %w", err)
	}

	return &card, nil
}
